import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import java.io.File

buildscript {
    repositories.mavenCentral()
    dependencies {
        classpath("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3")
        classpath("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    }
}

plugins {
    id("com.cheroliv.bakery") version "0.1.4"
}

val officePath: String = System.getenv("OFFICE_PATH") ?: "/home/cheroliv/workspace/office"
val workspaceRoot = File(System.getenv("HOME") ?: "/home/cheroliv").resolve("workspace")
val foundryDir = workspaceRoot.resolve("foundry/public")
val siteName: String = project.findProperty("siteName") as? String ?: "cheroliv.com"

bakery {
    configPath.set(file("$officePath/sites/$siteName/site.yml").path)
}

val dagLevels = mapOf(
    "graphify-gradle" to 0,
    "codebase-gradle" to 1,
    "bakery-gradle" to 2,
    "codex-gradle" to 2,
    "magic-stick" to 2,
    "planner-gradle" to 2,
    "plantuml-gradle" to 2,
    "quizz-benchmark-gradle" to 2,
    "quizz-benchmark-plugin" to 2,
    "readme-gradle" to 2,
    "slider-gradle" to 2,
    "training-gradle" to 2,
    "capsule-gradle" to 2,
    "engine" to 3,
    "waiter-plugin" to 2,
    "office-template" to 2,
    "jhipster-gradle-plugins" to 2,
    "notebook-gradle" to 2,
    "newpipe-gradle" to 2,
    "scripts" to 2,
    "site" to 2
)

val githubOrg = "cheroliv"
val pluginRepos = mapOf(
    "graphify-gradle" to "graphify-gradle",
    "codebase-gradle" to "codebase-gradle",
    "bakery-gradle" to "bakery-gradle",
    "codex-gradle" to "codex-gradle",
    "planner-gradle" to "planner-gradle",
    "plantuml-gradle" to "plantuml-gradle",
    "quizz-benchmark-gradle" to "quizz-benchmark-gradle",
    "readme-gradle" to "readme-gradle",
    "slider-gradle" to "slider-gradle",
    "training-gradle" to "training-gradle",
    "waiter-plugin" to "waiter-plugin",
    "jhipster-gradle-plugins" to "jhipster-gradle-plugins",
    "notebook-gradle" to "notebook-gradle",
    "newpipe-gradle" to "newpipe-gradle",
    "magic-stick" to "magic-stick",
    "engine" to "engine"
)

tasks.register("provisionWorkspace") {
    group = "engine"
    description = "Generates a provision.sh script to bootstrap a full workspace"

    val outputDir = project.layout.buildDirectory.dir("provision")
    val provisionScript = outputDir.map { it.file("provision.sh") }

    outputs.file(provisionScript)

    doLast {
        val dest = provisionScript.get().asFile
        dest.parentFile.mkdirs()
        dest.writeText(buildProvisionScript(dagLevels, pluginRepos))
        dest.setExecutable(true)

        println("Workspace provision script generated: ${dest.absolutePath}")
        println()
        println("To provision a workspace:")
        println("  chmod +x ${dest.absolutePath}")
        println("  ${dest.absolutePath} /path/to/workspace")
    }
}

fun buildProvisionScript(levels: Map<String, Int>, repos: Map<String, String>): String {
    val sb = StringBuilder()
    sb.appendLine("#!/usr/bin/env bash")
    sb.appendLine("# Engine - provision.sh - Bootstrap a full workspace from scratch")
    sb.appendLine("# Generated by: engine provisionWorkspace")
    sb.appendLine()
    sb.appendLine("set -euo pipefail")
    sb.appendLine()
    sb.appendLine("WS=\${1:-\$(pwd)/workspace}")
    sb.appendLine("echo \"Provisioning workspace at \$WS\"")
    sb.appendLine("mkdir -p \"\$WS\"/{foundry/public,office,office/sites,office/pilotage,configuration,configuration/.agents,configuration/vision-archive,configuration/settings}")
    sb.appendLine()

    val byLevel = levels.entries
        .filter { repos.containsKey(it.key) }
        .groupBy({ it.value }, { it.key })
        .toSortedMap()

    for ((level, projects) in byLevel) {
        sb.appendLine("# --- N$level projects ---")
        for (project in projects) {
            val repo = repos[project]!!
            sb.appendLine("echo \"  Cloning $project (N$level)...\"")
            sb.appendLine("if [ ! -d \"\$WS/foundry/public/$project\" ]; then")
            sb.appendLine("    git clone --depth 1 https://github.com/$githubOrg/$repo.git \"\$WS/foundry/public/$project\" 2>/dev/null || true")
            sb.appendLine("fi")
        }
        sb.appendLine()
    }

    sb.appendLine("# Engine at workspace root symlink")
    sb.appendLine("ln -sf \"\$WS/foundry/public/engine/engine.sh\" \"\$WS/engine\" 2>/dev/null || true")
    sb.appendLine()
    sb.appendLine("echo \"Workspace provisioned.\"")
    sb.appendLine("echo \"Next steps:\"")
    sb.appendLine("echo \"  cd \$WS/foundry/public/engine && ./gradlew tasks --group engine\"")

    return sb.toString()
}

tasks.register("info") {
    group = "engine"
    description = "Shows engine status: DAG levels, known plugins, workspace paths"

    doLast {
        println("============================================")
        println("  Engine v1.0 - N3 Orchestration")
        println("============================================")
        println()
        println("Workspace root : ${workspaceRoot.absolutePath}")
        println("Foundry (OSS)   : ${foundryDir.absolutePath}")
        println("Office          : $officePath")
        println("GitHub org      : $githubOrg")
        println()

        val byLevel = dagLevels.entries.groupBy({ it.value }, { it.key }).toSortedMap()
        println("-- DAG Registry (${dagLevels.size} projects) --")
        for ((level, projects) in byLevel) {
            println("  N$level: ${projects.joinToString(", ")}")
        }
        println()
        println("-- Engine Tasks --")
        println("  scanWorkspace       Graphify scan: workspace -> graph.json")
        println("  verifyDagAcyclic    Verify DAG acyclic rule (via graphify-plugin)")
        println("  provisionWorkspace  Generate workspace setup script")
        println("  info                This status display")
    }
}

tasks.register("apiSchema") {
    group = "engine"
    description = "Validates the OpenAPI 3.0 contract openapi.yaml for SaaS Edster"

    val contractFile = projectDir.resolve("openapi.yaml")

    doLast {
        if (!contractFile.exists()) {
            throw RuntimeException("openapi.yaml not found at ${contractFile.absolutePath}")
        }

        val content = contractFile.readText()

        val versionMatch = Regex("""^openapi:\s*["']?(\d+\.\d+\.\d+)""", RegexOption.MULTILINE)
            .find(content) ?: throw RuntimeException("Missing or invalid `openapi:` version")
        val version = versionMatch.groupValues[1]
        if (!version.startsWith("3.")) throw RuntimeException("openapi version must be 3.x, got: $version")

        val titleMatch = Regex("""^\s+title:\s*(.+)""", RegexOption.MULTILINE)
            .find(content) ?: throw RuntimeException("Missing `info.title`")
        val title = titleMatch.groupValues[1].trim()

        for (path in listOf("/health", "/provision", "/status")) {
            val quoted = Regex.escape(path)
            if (!Regex("""^\s+$quoted:""", RegexOption.MULTILINE).containsMatchIn(content))
                throw RuntimeException("Missing required path: $path")
        }

        for (schema in listOf(
            "HealthResponse", "ProvisionRequest", "ProvisionResponse",
            "StatusResponse", "PluginInfo", "ErrorResponse"
        )) {
            val quoted = Regex.escape(schema)
            if (!Regex("""^\s+$quoted:""", RegexOption.MULTILINE).containsMatchIn(content))
                throw RuntimeException("Missing required schema: $schema")
        }

        val pathCount = Regex("""^\s+/[a-z]+""", RegexOption.MULTILINE).findAll(content).count()
        val schemaCount = Regex("""^\s{4}\w+Response:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Request:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Info:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Error:""", RegexOption.MULTILINE).findAll(content).count()

        println("OpenAPI contract validated: $title")
        println("  Paths  : $pathCount")
        println("  Schemas: $schemaCount")
        println("  OK - ready for SaaS Edster")
    }
}

tasks.register("assembleCompositeContext") {
    group = "engine"
    description = "Pipeline N2->N3: codexRetrieve (cosine similarity pgvector) + codebaseRAG -> composite context vector"

    val workspaceRootDir = workspaceRoot
    val codexDir = foundryDir.resolve("codex-gradle")
    val trainingDir = foundryDir.resolve("training-gradle")
    val capsuleDir = foundryDir.resolve("capsule-gradle")
    val codebaseDir = foundryDir.resolve("codebase-gradle")
    val contextMode = project.findProperty("context") as? String ?: "composite"
    val query = project.findProperty("query") as? String ?: ""
    val topK = project.findProperty("topK") as? String ?: "5"
    val outputDir = layout.buildDirectory.dir("engine")

    doLast {
        val compositeOutput = outputDir.get().file("composite-context.json").asFile
        compositeOutput.parentFile.mkdirs()

        val codexEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite", "rag")) {
            if (codexDir.resolve("doc-pipeline").exists()) {
                val codexBuildDir = File(codexDir, "build/codex")
                codexBuildDir.mkdirs()
                val retrieveJson = File(codexBuildDir, "retrieve-results.json")

                println("[engine] codexRetrieve : \"${query.take(80)}\" -> pgvector (top-$topK)")
                val codexProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "codexRetrieve",
                    "-Pquery=$query",
                    "-PtopK=$topK",
                    "-PoutputFile=${retrieveJson.absolutePath}"
                ))
                    .directory(codexDir)
                    .redirectErrorStream(true)
                    .start()
                val codexExit = codexProc.waitFor()
                if (codexExit == 0 && retrieveJson.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(retrieveJson)
                    if (json is List<*>) {
                        for (item in json) {
                            if (item is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val map = item as Map<String, Any>
                                codexEntries.add(mapOf(
                                    "source" to "codex",
                                    "section" to (map["sectionPath"]?.toString() ?: ""),
                                    "similarity" to ((map["similarity"] as? Number)?.toDouble() ?: 0.0),
                                    "chunkText" to (map["chunkText"]?.toString() ?: "").take(500)
                                ))
                            }
                        }
                    }
                    println("[engine] OK codexRetrieve OK - ${codexEntries.size} results")
                } else {
                    println("[engine] codexRetrieve: pgvector not available (exit=$codexExit)")
                }
            } else {
                println("[engine] codex-gradle (N2) not found - skipping codexRetrieve")
            }
        }

        val trainingEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite", "rag")) {
            val trainingPluginDir = trainingDir.resolve("training-plugin")
            if (trainingPluginDir.exists()) {
                val trainingsBuildDir = File(trainingDir, "build/training")
                trainingsBuildDir.mkdirs()
                val retrieveJson = File(trainingsBuildDir, "retrieve-results.json")

                println("[engine] trainingRetrieve : \"${query.take(80)}\" -> pgvector (top-$topK)")
                val trainProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "trainingRetrieve",
                    "-Pquery=$query",
                    "-PtopK=$topK",
                    "-PoutputFile=${retrieveJson.absolutePath}"
                ))
                    .directory(trainingPluginDir)
                    .redirectErrorStream(true)
                    .start()
                val trainExit = trainProc.waitFor()
                if (trainExit == 0 && retrieveJson.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(retrieveJson)
                    if (json is List<*>) {
                        for (item in json) {
                            if (item is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val map = item as Map<String, Any>
                                trainingEntries.add(mapOf(
                                    "source" to "training",
                                    "entryId" to (map["entryId"]?.toString() ?: ""),
                                    "title" to (map["title"]?.toString() ?: ""),
                                    "similarity" to ((map["similarity"] as? Number)?.toDouble() ?: 0.0),
                                    "fullText" to (map["fullText"]?.toString() ?: "").take(500)
                                ))
                            }
                        }
                    }
                    println("[engine] OK trainingRetrieve OK - ${trainingEntries.size} results")
                } else {
                    println("[engine] trainingRetrieve: pgvector not available (exit=$trainExit)")
                }
            } else {
                println("[engine] training-gradle (N2) not found - skipping trainingRetrieve")
            }
        }

        val capsuleEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite")) {
            val capsulePluginDir = capsuleDir.resolve("capsule-plugin")
            if (capsulePluginDir.exists()) {
                println("[engine] capsuleCompositeContext")
                val capProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "capsulecompositecontext"
                ))
                    .directory(capsulePluginDir)
                    .redirectErrorStream(true)
                    .start()
                val capExit = capProc.waitFor()
                val capsuleJsonFile = File(capsulePluginDir, "build/capsule/capsule-context.json")
                if (capExit == 0 && capsuleJsonFile.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(capsuleJsonFile)
                    if (json is Map<*, *>) {
                        @Suppress("UNCHECKED_CAST")
                        val map = json as Map<String, Any>
                        val entries = map["entries"] as? List<*> ?: emptyList<Any>()
                        for (entry in entries) {
                            if (entry is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val em = entry as Map<String, Any>
                                capsuleEntries.add(mapOf(
                                    "source" to "capsule",
                                    "deckName" to (em["deckName"]?.toString() ?: ""),
                                    "slideCount" to ((em["slideCount"] as? Number)?.toInt() ?: 0),
                                    "originalVideo" to (em["originalVideo"]?.toString() ?: ""),
                                    "distribVideo" to (em["distribVideo"]?.toString() ?: ""),
                                    "ttsEngine" to (em["ttsEngine"]?.toString() ?: ""),
                                    "ttsVoice" to (em["ttsVoice"]?.toString() ?: "")
                                ))
                            }
                        }
                    }
                    println("[engine] OK capsuleCompositeContext OK - ${capsuleEntries.size} decks")
                } else {
                    println("[engine] capsuleCompositeContext: capsule not available (exit=$capExit)")
                }
            } else {
                println("[engine] capsule-gradle (N2) not found - skipping capsuleCompositeContext")
            }
        }

        if (contextMode in listOf("composite", "kg")) {
            val graphFile = workspaceRootDir.resolve("office/graph.json")
            if (graphFile.exists()) {
                val mapper = jacksonObjectMapper()
                val graph: Any = mapper.readValue(graphFile)
                if (graph is Map<*, *>) {
                    val nodeCount = (graph["nodes"] as? List<*>)?.size ?: 0
                    val edgeCount = (graph["edges"] as? List<*>)?.size ?: 0
                    println("[engine] Knowledge Graph: $nodeCount nodes, $edgeCount edges")
                }
            }
        }

        val codebaseContextFile = File("/tmp/opencode-context.txt")
        if (contextMode in listOf("composite", "sql", "rag")) {
            val buildFile = codebaseDir.resolve("build.gradle.kts")
            if (buildFile.exists()) {
                val hasAugment = buildFile.readText().contains("augmentOpencode")
                if (hasAugment) {
                    val cbProc = ProcessBuilder(listOf("./gradlew", "-q", "augmentOpencode"))
                        .directory(codebaseDir)
                        .redirectErrorStream(true)
                        .start()
                    cbProc.waitFor()
                }
            }
        }

        val result = mapOf(
            "query" to query,
            "mode" to contextMode,
            "codexResults" to codexEntries,
            "trainingResults" to trainingEntries,
            "capsuleResults" to capsuleEntries,
            "codebaseContextPath" to (if (codebaseContextFile.exists()) codebaseContextFile.absolutePath else ""),
            "timestamp" to System.currentTimeMillis()
        )

        val mapper = jacksonObjectMapper()
        compositeOutput.writeText(
            mapper.writerWithDefaultPrettyPrinter().writeValueAsString(result)
        )

        println("[engine] OK assembleCompositeContext - ${codexEntries.size} codex + ${trainingEntries.size} training + ${capsuleEntries.size} capsule + codebase -> ${compositeOutput.absolutePath}")
    }
}
