import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import java.io.File

buildscript {
    repositories.mavenCentral()
    dependencies {
        classpath("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3")
        classpath("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    }
}

plugins {
    id("education.cccp.bakery") version "0.1.4"
}

val officePath: String = System.getenv("OFFICE_PATH") ?: "/home/cheroliv/workspace/office"
val workspaceRoot = File(System.getenv("HOME") ?: "/home/cheroliv").resolve("workspace")
val foundryDir = workspaceRoot.resolve("foundry/public")
val siteName: String = project.findProperty("siteName") as? String ?: "cheroliv.com"

// HACK: utiliser un chemin relatif depuis engine/ pour contourner le bug
// File.resolve(cheminAbsolu) dans le bakery plugin v0.1.4.
// Le plugin utilise File(File parent, String child) qui concatène avec les
// chemins absolus au lieu de les remplacer.
val siteConfigFile = file("$officePath/sites/$siteName/site.yml")
val relativeConfigPath = project.layout.projectDirectory.asFile
    .toPath()
    .relativize(siteConfigFile.toPath())
    .toString()

bakery {
    configPath.set(relativeConfigPath)
}

val dagLevels = mapOf(
    "graphify-gradle" to 0,
    "codebase-gradle" to 1,
    "bakery-gradle" to 2,
    "codex-gradle" to 2,
    "magic-stick" to 2,
    "planner-gradle" to 2,
    "plantuml-gradle" to 2,
    "quizz-benchmark-gradle" to 2,
    "quizz-benchmark-plugin" to 2,
    "readme-gradle" to 2,
    "slider-gradle" to 2,
    "training-gradle" to 2,
    "capsule-gradle" to 2,
    "engine" to 3,
    "waiter-plugin" to 2,
    "office-template" to 2,
    "jhipster-gradle-plugins" to 2,
    "notebook-gradle" to 2,
    "newpipe-gradle" to 2,
    "scripts" to 2,
    "site" to 2
)

val githubOrg = "cheroliv"
val pluginRepos = mapOf(
    "graphify-gradle" to "graphify-gradle",
    "codebase-gradle" to "codebase-gradle",
    "bakery-gradle" to "bakery-gradle",
    "codex-gradle" to "codex-gradle",
    "planner-gradle" to "planner-gradle",
    "plantuml-gradle" to "plantuml-gradle",
    "quizz-benchmark-gradle" to "quizz-benchmark-gradle",
    "readme-gradle" to "readme-gradle",
    "slider-gradle" to "slider-gradle",
    "training-gradle" to "training-gradle",
    "waiter-plugin" to "waiter-plugin",
    "jhipster-gradle-plugins" to "jhipster-gradle-plugins",
    "notebook-gradle" to "notebook-gradle",
    "newpipe-gradle" to "newpipe-gradle",
    "magic-stick" to "magic-stick",
    "engine" to "engine"
)

tasks.register("deployWorkspace") {
    group = "deploy"
    description = "Generates a provision.sh script to bootstrap a full workspace"

    val outputDir = project.layout.buildDirectory.dir("provision")
    val provisionScript = outputDir.map { it.file("provision.sh") }

    outputs.file(provisionScript)

    doLast {
        val dest = provisionScript.get().asFile
        dest.parentFile.mkdirs()
        dest.writeText(buildProvisionScript(dagLevels, pluginRepos))
        dest.setExecutable(true)

        println("Workspace provision script generated: ${dest.absolutePath}")
        println()
        println("To provision a workspace:")
        println("  chmod +x ${dest.absolutePath}")
        println("  ${dest.absolutePath} /path/to/workspace")
    }
}

fun buildProvisionScript(levels: Map<String, Int>, repos: Map<String, String>): String {
    val sb = StringBuilder()
    sb.appendLine("#!/usr/bin/env bash")
    sb.appendLine("# Engine - provision.sh - Bootstrap a full workspace from scratch")
    sb.appendLine("# Generated by: engine deployWorkspace")
    sb.appendLine()
    sb.appendLine("set -euo pipefail")
    sb.appendLine()
    sb.appendLine("WS=\${1:-\$(pwd)/workspace}")
    sb.appendLine("echo \"Provisioning workspace at \$WS\"")
    sb.appendLine("mkdir -p \"\$WS\"/{foundry/public,office,office/sites,office/pilotage,configuration,configuration/.agents,configuration/vision-archive,configuration/settings}")
    sb.appendLine()

    val byLevel = levels.entries
        .filter { repos.containsKey(it.key) }
        .groupBy({ it.value }, { it.key })
        .toSortedMap()

    for ((level, projects) in byLevel) {
        sb.appendLine("# --- N$level projects ---")
        for (project in projects) {
            val repo = repos[project]!!
            sb.appendLine("echo \"  Cloning $project (N$level)...\"")
            sb.appendLine("if [ ! -d \"\$WS/foundry/public/$project\" ]; then")
            sb.appendLine("    git clone --depth 1 https://github.com/$githubOrg/$repo.git \"\$WS/foundry/public/$project\" 2>/dev/null || true")
            sb.appendLine("fi")
        }
        sb.appendLine()
    }

    sb.appendLine("# Engine at workspace root symlink")
    sb.appendLine("ln -sf \"\$WS/foundry/public/engine/engine.sh\" \"\$WS/engine\" 2>/dev/null || true")
    sb.appendLine()
    sb.appendLine("echo \"Workspace provisioned.\"")
    sb.appendLine("echo \"Next steps:\"")
    sb.appendLine("echo \"  cd \$WS/foundry/public/engine && ./gradlew tasks --group engine\"")

    return sb.toString()
}

tasks.register("info") {
    group = "info"
    description = "Shows engine status: DAG levels, known plugins, workspace paths"

    doLast {
        println("============================================")
        println("  Engine v1.0 - N3 Orchestration")
        println("============================================")
        println()
        println("Workspace root : ${workspaceRoot.absolutePath}")
        println("Foundry (OSS)   : ${foundryDir.absolutePath}")
        println("Office          : $officePath")
        println("GitHub org      : $githubOrg")
        println()

        val byLevel = dagLevels.entries.groupBy({ it.value }, { it.key }).toSortedMap()
        println("-- DAG Registry (${dagLevels.size} projects) --")
        for ((level, projects) in byLevel) {
            println("  N$level: ${projects.joinToString(", ")}")
        }
        println()
        println("-- Engine Tasks --")
        println("  scanWorkspace       Graphify scan: workspace -> graph.json")
        println("  verifyDagAcyclic    Verify DAG acyclic rule (via graphify-plugin)")
        println("  deployWorkspace     Generate workspace setup script")
        println("  info                This status display")
    }
}

tasks.register("generateApiSchema") {
    group = "generate"
    description = "Validates the OpenAPI 3.0 contract openapi.yaml for SaaS Edster"

    val contractFile = projectDir.resolve("openapi.yaml")

    doLast {
        if (!contractFile.exists()) {
            throw RuntimeException("openapi.yaml not found at ${contractFile.absolutePath}")
        }

        val content = contractFile.readText()

        val versionMatch = Regex("""^openapi:\s*["']?(\d+\.\d+\.\d+)""", RegexOption.MULTILINE)
            .find(content) ?: throw RuntimeException("Missing or invalid `openapi:` version")
        val version = versionMatch.groupValues[1]
        if (!version.startsWith("3.")) throw RuntimeException("openapi version must be 3.x, got: $version")

        val titleMatch = Regex("""^\s+title:\s*(.+)""", RegexOption.MULTILINE)
            .find(content) ?: throw RuntimeException("Missing `info.title`")
        val title = titleMatch.groupValues[1].trim()

        for (path in listOf("/health", "/provision", "/status")) {
            val quoted = Regex.escape(path)
            if (!Regex("""^\s+$quoted:""", RegexOption.MULTILINE).containsMatchIn(content))
                throw RuntimeException("Missing required path: $path")
        }

        for (schema in listOf(
            "HealthResponse", "ProvisionRequest", "ProvisionResponse",
            "StatusResponse", "PluginInfo", "ErrorResponse"
        )) {
            val quoted = Regex.escape(schema)
            if (!Regex("""^\s+$quoted:""", RegexOption.MULTILINE).containsMatchIn(content))
                throw RuntimeException("Missing required schema: $schema")
        }

        val pathCount = Regex("""^\s+/[a-z]+""", RegexOption.MULTILINE).findAll(content).count()
        val schemaCount = Regex("""^\s{4}\w+Response:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Request:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Info:""", RegexOption.MULTILINE).findAll(content).count() +
                          Regex("""^\s{4}\w+Error:""", RegexOption.MULTILINE).findAll(content).count()

        println("OpenAPI contract validated: $title")
        println("  Paths  : $pathCount")
        println("  Schemas: $schemaCount")
        println("  OK - ready for SaaS Edster")
    }
}

tasks.register("collectCompositeContext") {
    group = "collect"
    description = "Pipeline N0→N3 complet : graphify scan (N0) + codebaseRAG (N1) + codex/training/capsule (N2) → composite context vector"

    val workspaceRootDir = workspaceRoot
    val graphifyDir = foundryDir.resolve("graphify-gradle")
    val codexDir = foundryDir.resolve("codex-gradle")
    val trainingDir = foundryDir.resolve("training-gradle")
    val capsuleDir = foundryDir.resolve("capsule-gradle")
    val codebaseDir = foundryDir.resolve("codebase-gradle")
    val contextMode = project.findProperty("context") as? String ?: "composite"
    val query = project.findProperty("query") as? String ?: ""
    val topK = project.findProperty("topK") as? String ?: "5"
    val outputDir = layout.buildDirectory.dir("engine")
    val skipGraphify = project.findProperty("skipGraphify")?.toString()?.toBoolean() ?: false

    doLast {
        val compositeOutput = outputDir.get().file("composite-context.json").asFile
        compositeOutput.parentFile.mkdirs()

        // ── Phase 0: Graphify — Knowledge Graph (N0) ──
        val graphifyEntries = ArrayList<Map<String, Any>>()

        if (!skipGraphify && graphifyDir.resolve("build.gradle.kts").exists()) {
            println("[engine] collectFromWorkspace (N0 — graphify) : scanning workspace → graph.json")
            val gfProc = ProcessBuilder(listOf("./gradlew", "-q", "collectFromWorkspace"))
                .directory(graphifyDir)
                .redirectErrorStream(true)
                .start()
            val gfExit = gfProc.waitFor()
            val graphFile = workspaceRootDir.resolve("office/graph.json")
            if (gfExit == 0 && graphFile.exists()) {
                val mapper = jacksonObjectMapper()
                val graph: Any = mapper.readValue(graphFile)
                if (graph is Map<*, *>) {
                    @Suppress("UNCHECKED_CAST")
                    val g = graph as Map<String, Any>
                    val nodeCount = (g["nodes"] as? List<*>)?.size ?: 0
                    val edgeCount = (g["edges"] as? List<*>)?.size ?: 0
                    println("[engine] OK collectFromWorkspace OK — $nodeCount nodes, $edgeCount edges")
                    graphifyEntries.add(mapOf(
                        "source" to "graphify",
                        "nodes" to nodeCount,
                        "edges" to edgeCount
                    ))
                }
            } else {
                println("[engine] collectFromWorkspace : échec (exit=$gfExit)")
            }
        } else if (skipGraphify) {
            println("[engine] collectFromWorkspace : skipped (--skipGraphify)")
        }

        // ── Phase 1: Codex (N2) — pgvector cosine similarity ──
        val codexEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite", "rag")) {
            if (codexDir.resolve("doc-pipeline").exists()) {
                val codexBuildDir = File(codexDir, "build/codex")
                codexBuildDir.mkdirs()
                val retrieveJson = File(codexBuildDir, "retrieve-results.json")

                println("[engine] codexRetrieve : \"${query.take(80)}\" -> pgvector (top-$topK)")
                val codexProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "codexRetrieve",
                    "-Pquery=$query",
                    "-PtopK=$topK",
                    "-PoutputFile=${retrieveJson.absolutePath}"
                ))
                    .directory(codexDir)
                    .redirectErrorStream(true)
                    .start()
                val codexExit = codexProc.waitFor()
                if (codexExit == 0 && retrieveJson.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(retrieveJson)
                    if (json is List<*>) {
                        for (item in json) {
                            if (item is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val map = item as Map<String, Any>
                                codexEntries.add(mapOf(
                                    "source" to "codex",
                                    "section" to (map["sectionPath"]?.toString() ?: ""),
                                    "similarity" to ((map["similarity"] as? Number)?.toDouble() ?: 0.0),
                                    "chunkText" to (map["chunkText"]?.toString() ?: "").take(500)
                                ))
                            }
                        }
                    }
                    println("[engine] OK codexRetrieve OK - ${codexEntries.size} results")
                } else {
                    println("[engine] codexRetrieve: pgvector not available (exit=$codexExit)")
                }
            } else {
                println("[engine] codex-gradle (N2) not found - skipping codexRetrieve")
            }
        }

        val trainingEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite", "rag")) {
            val trainingPluginDir = trainingDir.resolve("training-plugin")
            if (trainingPluginDir.exists()) {
                val trainingsBuildDir = File(trainingDir, "build/training")
                trainingsBuildDir.mkdirs()
                val retrieveJson = File(trainingsBuildDir, "retrieve-results.json")

                println("[engine] collectFromCorpus : \"${query.take(80)}\" -> pgvector (top-$topK)")
                val trainProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "collectFromCorpus",
                    "-Pquery=$query",
                    "-PtopK=$topK",
                    "-PoutputFile=${retrieveJson.absolutePath}"
                ))
                    .directory(trainingPluginDir)
                    .redirectErrorStream(true)
                    .start()
                val trainExit = trainProc.waitFor()
                if (trainExit == 0 && retrieveJson.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(retrieveJson)
                    if (json is List<*>) {
                        for (item in json) {
                            if (item is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val map = item as Map<String, Any>
                                trainingEntries.add(mapOf(
                                    "source" to "training",
                                    "entryId" to (map["entryId"]?.toString() ?: ""),
                                    "title" to (map["title"]?.toString() ?: ""),
                                    "similarity" to ((map["similarity"] as? Number)?.toDouble() ?: 0.0),
                                    "fullText" to (map["fullText"]?.toString() ?: "").take(500)
                                ))
                            }
                        }
                    }
                    println("[engine] OK collectFromCorpus OK - ${trainingEntries.size} results")
                } else {
                    println("[engine] collectFromCorpus: pgvector not available (exit=$trainExit)")
                }
            } else {
                println("[engine] training-gradle (N2) not found - skipping collectFromCorpus")
            }
        }

        val capsuleEntries = ArrayList<Map<String, Any>>()

        if (contextMode in listOf("composite")) {
            val capsulePluginDir = capsuleDir.resolve("capsule-plugin")
            if (capsulePluginDir.exists()) {
                println("[engine] capsuleCompositeContext")
                val capProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "capsulecompositecontext"
                ))
                    .directory(capsulePluginDir)
                    .redirectErrorStream(true)
                    .start()
                val capExit = capProc.waitFor()
                val capsuleJsonFile = File(capsulePluginDir, "build/capsule/capsule-context.json")
                if (capExit == 0 && capsuleJsonFile.exists()) {
                    val mapper = jacksonObjectMapper()
                    val json: Any = mapper.readValue(capsuleJsonFile)
                    if (json is Map<*, *>) {
                        @Suppress("UNCHECKED_CAST")
                        val map = json as Map<String, Any>
                        val entries = map["entries"] as? List<*> ?: emptyList<Any>()
                        for (entry in entries) {
                            if (entry is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val em = entry as Map<String, Any>
                                capsuleEntries.add(mapOf(
                                    "source" to "capsule",
                                    "deckName" to (em["deckName"]?.toString() ?: ""),
                                    "slideCount" to ((em["slideCount"] as? Number)?.toInt() ?: 0),
                                    "originalVideo" to (em["originalVideo"]?.toString() ?: ""),
                                    "distribVideo" to (em["distribVideo"]?.toString() ?: ""),
                                    "ttsEngine" to (em["ttsEngine"]?.toString() ?: ""),
                                    "ttsVoice" to (em["ttsVoice"]?.toString() ?: "")
                                ))
                            }
                        }
                    }
                    println("[engine] OK capsuleCompositeContext OK - ${capsuleEntries.size} decks")
                } else {
                    println("[engine] capsuleCompositeContext: capsule not available (exit=$capExit)")
                }
            } else {
                println("[engine] capsule-gradle (N2) not found - skipping capsuleCompositeContext")
            }
        }

        // ── Phase 4: Codebase-gradle (N1) — Composite Context ──
        val codebaseEntries = ArrayList<Map<String, Any>>()
        val codebaseContextFile = File("/tmp/opencode-context.txt")

        if (contextMode in listOf("composite", "rag")) {
            val codebasePluginDir = codebaseDir.resolve("codebase-plugin")
            if (codebasePluginDir.exists()) {
                println("[engine] collectFromCodebase : pgvector indexing + composite context (EAGER+RAG+Graphify)")
                val cbProc = ProcessBuilder(listOf(
                    "./gradlew", "-q", "collectFromCodebase",
                    "-PragQuestion=architecture du workspace"
                ))
                    .directory(codebasePluginDir)
                    .redirectErrorStream(true)
                    .start()
                val cbExit = cbProc.waitFor()

                if (cbExit == 0) {
                    // Lire le contexte composite produit par codebase-gradle
                    val workspaceContextFile = File(codebasePluginDir, "build/context/workspace-context.txt")
                    if (workspaceContextFile.exists()) {
                        val ctxContent = workspaceContextFile.readText()
                        codebaseEntries.add(mapOf(
                            "source" to "codebase",
                            "contextSize" to workspaceContextFile.length(),
                            "contextLines" to ctxContent.lines().size,
                            "contextPreview" to ctxContent.take(500)
                        ))
                        println("[engine] OK collectFromCodebase OK — ${workspaceContextFile.length()} bytes, ${ctxContent.lines().size} lines")
                    } else {
                        println("[engine] collectFromCodebase : OK mais workspace-context.txt non trouvé")
                    }
                } else {
                    println("[engine] collectFromCodebase : pgvector not available (exit=$cbExit)")
                }
            } else {
                // Fallback : codebase-plugin/ absent → utiliser codebase-gradle/ racine
                val buildFile = codebaseDir.resolve("build.gradle.kts")
                if (buildFile.exists()) {
                    println("[engine] collectFromCodebase : codebase-plugin/ absent, tentative racine codebase-gradle/")
                    val cbProc = ProcessBuilder(listOf("./gradlew", "-q", "collectFromCodebase"))
                        .directory(codebaseDir)
                        .redirectErrorStream(true)
                        .start()
                    val cbExit = cbProc.waitFor()
                    if (cbExit == 0) {
                        codebaseEntries.add(mapOf(
                            "source" to "codebase",
                            "status" to "collected via racine codebase-gradle/"
                        ))
                        println("[engine] OK collectFromCodebase OK (fallback)")
                    } else {
                        println("[engine] collectFromCodebase : échec fallback (exit=$cbExit)")
                    }
                } else {
                    println("[engine] codebase-gradle (N1) not found — skipping composite context")
                }
            }
        }

        val result = mapOf(
            "query" to query,
            "mode" to contextMode,
            "graphify" to graphifyEntries,
            "codexResults" to codexEntries,
            "trainingResults" to trainingEntries,
            "capsuleResults" to capsuleEntries,
            "codebaseResults" to codebaseEntries,
            "codebaseContextPath" to (if (codebaseContextFile.exists()) codebaseContextFile.absolutePath else ""),
            "timestamp" to System.currentTimeMillis()
        )

        val mapper = jacksonObjectMapper()
        compositeOutput.writeText(
            mapper.writerWithDefaultPrettyPrinter().writeValueAsString(result)
        )

        println("[engine] OK collectCompositeContext — N0:graphify(${graphifyEntries.size}) N1:codebase(${codebaseEntries.size}) + N2:codex(${codexEntries.size})/training(${trainingEntries.size})/capsule(${capsuleEntries.size}) → ${compositeOutput.absolutePath}")
    }
}

// ── EPIC K-04 : verifyBoroughs ──────────────────────────────
// Convention over Configuration — valide les 11 boroughs contre le contrat
// TAXONOMIE_WORKSPACE.adoc : existence, gouvernance agent, metadata.json,
// inférence depuis l'arborescence, cohérence DAG.
// ──────────────────────────────────────────────────────────────────────

data class BoroughDef(
    val name: String,           // Nom affiché (ex: "Newark")
    val dirPath: String,        // Chemin absolu du répertoire
    val dagLevel: Int,          // 0..4 ou -1 pour N-IDE
    val dagLabel: String,       // "N0", "N1", "N2", "N3", "N4", "N-IDE"
    val role: String,           // "producteur", "consommateur", "orchestrateur", "deployeur", "pilotage", "interface"
    val producesMetadata: Boolean, // true si doit produire metadata.json
    val dataDir: String?,       // Répertoire de données pour inférence (ex: "data/formations/")
    val metadataExpectedPath: String?, // Chemin où metadata.json est attendu
    val extensionNamespace: String?, // Namespace DSL attendu (ex: "training", "planner", "codex", null si N/A)
    val extensionClassHint: String? // Indice pour trouver la classe Extension (ex: "TrainingExtension")
)

val workspaceDir = File(System.getenv("HOME") ?: "/home/cheroliv").resolve("workspace").absoluteFile

val boroughs = listOf(
    BoroughDef("Newark",        "$workspaceDir/foundry/public/training-gradle",            2, "N2",   "producteur",     true,  "src/main/data/formations",    "build/dataset/metadata.json",     "training", "TrainingExtension"),
    BoroughDef("Manhattan",     "$workspaceDir/foundry/public/planner-gradle",              2, "N2",   "producteur",     true,  null,                          "build/spg/metadata.json",         "planner",  "PlannerExtension"),
    BoroughDef("Brooklyn",      "$workspaceDir/foundry/public/codex-gradle",                2, "N2",   "producteur",     true,  "src/main/data/books",          null,                               "codex",    "CodexExtension"),
    // Brooklyn metadata.json path depends on consumer outputFile config — no fixed convention
    BoroughDef("Queens",        "$workspaceDir/foundry/public/codebase-gradle",             1, "N1",   "producteur",     true,  null,                          "build/rag/metadata.json",         "codebase", "CodebaseExtension"),
    BoroughDef("The Bronx",     "$workspaceDir/foundry/public/quizz-benchmark-gradle",      2, "N2",   "producteur",     true,  null,                          "build/quiz-reports/generated/metadata.json",   "quiz",     "QuizExtension"),
    BoroughDef("Staten Island", "$workspaceDir/office/sites/magic-stick",                   2, "N2",   "deployeur",      false, null,                          null,                         null,       null),
    BoroughDef("New Jersey",    "$workspaceDir/foundry/public/engine",                      3, "N3",   "orchestrateur",  false, null,                          null,                         null,       null),
    BoroughDef("Compton",       "$workspaceDir/foundry/private/waiter-gradle",              2, "N2",   "consommateur",   false, null,                          null,                         null,       null),
    BoroughDef("Brooklyn Tech", "$workspaceDir/foundry/public/capsule-gradle",              2, "N2",   "producteur",     true,  null,                          "build/capsule/metadata.json","capsule",  "CapsuleExtension"),
    BoroughDef("South Central", "$workspaceDir/foundry/private/workspace-gradle",           4, "N4",   "pilotage",       false, null,                          null,                         null,       null),
    BoroughDef("Long Island",   "$workspaceDir/intellij-plugins/workspace-agent",          -1, "N-IDE","interface",      false, null,                          null,                         null,       null)
)

// Boroughs en attente de bootstrap gouvernance (IJ-0 CADRE dans PLAN_GLOBAL)
val preBootstrapBoroughs = setOf("Long Island")

tasks.register("verifyBoroughs") {
    group = "verify"
    description = "Validates metadata contracts for all 11 boroughs (EPIC K-04 Convention over Configuration)"

    doLast {
        val results = mutableListOf<Map<String, Any>>()
        var criticalFails = 0
        var warnings = 0
        var pass = 0

        println("=" .repeat(72))
        println("  EPIC K-04 — verifyBoroughs")
        println("  Convention over Configuration — TAXONOMIE_WORKSPACE.adoc")
        println("=" .repeat(72))
        println()

        for (b in boroughs) {
            println("── ${b.name} (${b.dagLabel}) — ${b.role} ──")
            val checks = mutableListOf<String>()
            val failures = mutableListOf<String>()
            val warns = mutableListOf<String>()

            // 1. Existence du répertoire
            val dir = File(b.dirPath)
            if (!dir.exists() || !dir.isDirectory) {
                failures.add("CRITICAL: répertoire absent — ${b.dirPath}")
                results.add(mapOf("borough" to b.name, "status" to "FAIL", "checks" to failures))
                criticalFails++
                println("  ❌ DIR  absent : ${b.dirPath}")
                println()
                continue
            }
            checks.add("DIR présent")

            // 2. AGENT.adoc (cherche récursivement : racine ou sous-répertoire type xxx-plugin/)
            val agentFile = findFileRecursive(dir, "AGENT.adoc", maxDepth = 3)
            if (agentFile != null) {
                checks.add("AGENT.adoc")
            } else if (b.name in preBootstrapBoroughs) {
                warns.add("AGENT.adoc manquant — pré-bootstrap, CADRE dans PLAN_GLOBAL")
            } else {
                failures.add("CRITICAL: AGENT.adoc manquant")
            }

            // 3. .agents/INDEX.adoc (cherche récursivement : racine ou sous-répertoire)
            val indexFile = findFileRecursive(dir, ".agents/INDEX.adoc", maxDepth = 3)
            if (indexFile != null) {
                checks.add(".agents/INDEX.adoc")
            } else if (b.name in preBootstrapBoroughs) {
                warns.add(".agents/INDEX.adoc manquant — pré-bootstrap, CADRE dans PLAN_GLOBAL")
            } else {
                failures.add("CRITICAL: .agents/INDEX.adoc manquant")
            }

            // 4. metadata.json pour les producteurs
            val metadataFile = if (b.metadataExpectedPath != null) {
                File(dir, b.metadataExpectedPath)
            } else null

            if (b.producesMetadata) {
                checks.add("metadata.json attendu (${b.metadataExpectedPath})")
                if (metadataFile != null && metadataFile.exists()) {
                    checks.add("metadata.json présent")
                    // Valider le contenu
                    try {
                        val mapper = jacksonObjectMapper()
                        val content: Any = mapper.readValue(metadataFile)
                        val missingFields = mutableListOf<String>()

                        if (content is Map<*, *>) {
                            @Suppress("UNCHECKED_CAST")
                            val map = content as Map<String, Any?>
                            val requiredFields = listOf("source", "type", "version")
                            for (field in requiredFields) {
                                val v = map[field]
                                if (v == null || (v is String && v.isBlank()))
                                    missingFields.add(field)
                            }
                        } else if (content is List<*>) {
                            // metadata.json = tableau → vérifier le premier élément
                            val first = content.firstOrNull()
                            if (first is Map<*, *>) {
                                @Suppress("UNCHECKED_CAST")
                                val map = first as Map<String, Any?>
                                val requiredFields = listOf("source", "type", "version")
                                for (field in requiredFields) {
                                    val v = map[field]
                                    if (v == null || (v is String && v.isBlank()))
                                        missingFields.add(field)
                                }
                            }
                        }

                        if (missingFields.isEmpty()) {
                            checks.add("metadata.json valide")
                        } else {
                            warns.add("metadata.json : champs requis manquants — ${missingFields.joinToString(", ")}")
                        }
                    } catch (e: Exception) {
                        warns.add("metadata.json : parse error — ${e.message}")
                    }
                } else {
                    warns.add("metadata.json manquant — doit être produit par le plugin N2 (build/spg/ ou équivalent)")
                }
            } else {
                checks.add("metadata.json non requis (${b.role})")
            }

            // 4. Extension DSL (K-3 Configuration par domaine)
            if (b.extensionNamespace != null) {
                val extNs = b.extensionNamespace
                val extFound = findExtensionRegistration(dir, extNs, maxDepth = 8)
                if (extFound != null) {
                    checks.add("Extension DSL : namespace \"$extNs\" enregistré (${extFound.name})")
                } else {
                    warns.add("Extension \"$extNs\" non enregistrée — K-3 en attente ?")
                }
            } else {
                checks.add("Extension DSL non requis (${b.role})")
            }

            // 5. Inférence des métadonnées depuis l'arborescence
            if (b.dataDir != null) {
                val inferred = inferMetadataFromFilesystem(File(dir, b.dataDir), b.name)
                if (inferred != null) {
                    checks.add("inférence arborescence OK — ${inferred["moduleCount"]} modules, ${inferred["sessionCount"]} sessions")
                } else {
                    // Pas de données à inférer, ce n'est pas un échec
                    checks.add("inférence arborescence : pas de données trouvées")
                }
            }

            // Rapport
            if (failures.isEmpty() && warns.isEmpty()) {
                println("  ✅ PASS — ${checks.joinToString(", ")}")
                results.add(mapOf("borough" to b.name, "status" to "PASS", "checks" to checks))
                pass++
            } else if (failures.isEmpty()) {
                println("  ⚠️  WARN — ${warns.joinToString("; ")}")
                println("     CHECK — ${checks.joinToString(", ")}")
                results.add(mapOf("borough" to b.name, "status" to "WARN", "checks" to checks, "warnings" to warns))
                warnings++
            } else {
                println("  ❌ FAIL — ${failures.joinToString("; ")}")
                if (warns.isNotEmpty()) println("     WARN — ${warns.joinToString("; ")}")
                println("     CHECK — ${checks.joinToString(", ")}")
                results.add(mapOf("borough" to b.name, "status" to "FAIL", "checks" to checks, "failures" to failures, "warnings" to warns))
                criticalFails++
            }
            println()
        }

        // Résumé
        println("=" .repeat(72))
        println("  RÉSUMÉ : ${pass} PASS / ${warnings} WARN / ${criticalFails} FAIL")
        println("=" .repeat(72))
        println()
        val rows = results.joinToString("\n") { r ->
            val name = (r["borough"] as String).padEnd(16)
            val status = r["status"] as String
            val icon = when(status) { "PASS" -> "✅"; "WARN" -> "⚠️"; else -> "❌" }
            "  $icon $name $status"
        }
        println(rows)

        if (criticalFails > 0) {
            throw RuntimeException("verifyBoroughs: $criticalFails CRITICAL failure(s). Fix before publishing.")
        }
    }
}

/**
 * Cherche récursivement un fichier dans un répertoire jusqu'à maxDepth.
 * Retourne le fichier trouvé, ou null.
 * Pour les boroughs où AGENT.adoc/.agents/ est dans un sous-répertoire (ex: xxx-plugin/).
 */
fun findFileRecursive(dir: File, name: String, maxDepth: Int): File? {
    if (!dir.isDirectory) return null
    val direct = File(dir, name)
    if (direct.exists()) return direct
    if (maxDepth <= 0) return null
    val children = dir.listFiles()?.filter { it.isDirectory } ?: emptyList()
    for (child in children) {
        // Ignorer .git, build, .gradle, .idea, bin, out
        if (child.name in setOf(".git", "build", ".gradle", ".idea", "bin", "out", "node_modules"))
            continue
        // Pour .agents/INDEX.adoc, chercher dans le sous-répertoire .agents/ directement
        if (name.contains("/")) {
            val parts = name.split("/")
            val subDir = parts.dropLast(1).fold(dir) { acc, part -> File(acc, part) }
            val subFile = File(subDir, parts.last())
            if (subFile.exists()) return subFile
        }
        val found = findFileRecursive(child, name, maxDepth - 1)
        if (found != null) return found
    }
    return null
}

/**
 * Cherche l'enregistrement d'une extension Gradle (extensions.create("namespace")) dans les
 * sources Kotlin d'un borough, jusqu'à maxDepth. Retourne le fichier contenant l'appel, ou null.
 */
fun findExtensionRegistration(dir: File, namespace: String, maxDepth: Int): File? {
    if (!dir.isDirectory) return null
    if (maxDepth <= 0) return null

    val kotlinFiles = dir.listFiles()?.filter {
        it.isFile && it.extension == "kt"
    } ?: emptyList()

    for (file in kotlinFiles) {
        try {
            val content = file.readText()
            // Cherche extensions.create("namespace") ou extensions.create<...>("namespace")
            val pattern = Regex("""extensions\.create\s*[<(].*["']$namespace["']""")
            if (pattern.containsMatchIn(content)) return file
        } catch (_: Exception) { /* skip unreadable files */ }
    }

    // Explorer récursivement les sous-répertoires
    val children = dir.listFiles()?.filter { it.isDirectory } ?: emptyList()
    for (child in children) {
        if (child.name in setOf(".git", "build", ".gradle", ".idea", "bin", "out", "node_modules"))
            continue
        val found = findExtensionRegistration(child, namespace, maxDepth - 1)
        if (found != null) return found
    }
    return null
}

/**
 * Infère les métadonnées d'un borough producteur depuis la structure
 * de son arborescence de données (Convention Over Configuration).
 *
 * Implémente les règles de TAXONOMIE_WORKSPACE.adoc § Convention Over Configuration :
 * - Module   : nom du dossier parent, strip préfixe numérique
 * - Ordre    : préfixe numérique du fichier/dossier
 * - Statut   : published par défaut, draft si préfixé par _
 * - Titre    : premier titre de niveau 1 (= Titre) dans le fichier
 * - Type     : inféré du dossier racine
 * - Magic value -987654321 pour index.adoc
 */
fun inferMetadataFromFilesystem(dataDir: File, boroughName: String): Map<String, Any>? {
    if (!dataDir.exists() || !dataDir.isDirectory) return null

    val modules = mutableListOf<Map<String, Any>>()
    var totalSessions = 0

    val dirEntries = dataDir.listFiles()?.filter { it.isDirectory }?.sortedBy { it.name } ?: emptyList()
    for (moduleDir in dirEntries) {
        val moduleName = moduleDir.name.replace(Regex("^\\d+_"), "")
        val adocFiles = moduleDir.listFiles()?.filter {
            it.extension == "adoc" && !it.name.startsWith("index")
        }?.sortedBy { it.name } ?: emptyList()

        val sessions = mutableListOf<Map<String, Any>>()

        for ((idx, file) in adocFiles.withIndex()) {
            val orderPrefix = Regex("^(\\d+)_").find(file.name)?.groupValues?.get(1)
            val order = orderPrefix?.toIntOrNull() ?: (idx + 1)
            val isDraft = file.name.startsWith("_")
            val title = extractAdocTitle(file)
            val actualName = file.name.replace(Regex("^\\d+_"), "").replace(".adoc", "")
            sessions.add(mapOf(
                "file" to file.name,
                "title" to (title ?: actualName),
                "order" to order,
                "status" to if (isDraft) "draft" else "published"
            ))
            totalSessions++
        }

        // Vérifier index.adoc
        val indexFile = File(moduleDir, "index.adoc")
        val hasIndex = indexFile.exists()

        modules.add(mapOf(
            "module" to moduleName,
            "order" to (dirEntries.indexOf(moduleDir) + 1),
            "sessions" to sessions,
            "sessionCount" to sessions.size,
            "hasIndex" to hasIndex
        ))
    }

    val type = when {
        dataDir.name.contains("formation", ignoreCase = true) -> "formation"
        dataDir.name.contains("evaluation", ignoreCase = true) -> "quiz"
        dataDir.name.contains("book", ignoreCase = true) -> "book"
        else -> "content"
    }

    return mapOf(
        "source" to boroughName,
        "type" to type,
        "modules" to modules,
        "moduleCount" to modules.size,
        "sessionCount" to totalSessions,
        "inferred" to true,
        "convention" to "TAXONOMIE_WORKSPACE.adoc § Convention Over Configuration"
    )
}

/**
 * Extrait le premier titre de niveau 1 (= Titre) d'un fichier AsciiDoc.
 * Retourne null si aucun titre trouvé.
 */
fun extractAdocTitle(file: File): String? {
    if (!file.exists()) return null
    val firstLine = file.useLines { lines ->
        lines.firstOrNull { it.startsWith("= ") && !it.startsWith("== ") }
    }
    return firstLine?.removePrefix("= ")?.trim()
}
